### ISSUE TITLE
Why the choice of the docker image is illegal?

### ISSUE THREAD

**Issue by zhoufengfan** [mzhaoshuai/SplitNet-Divide-and-Co-training#5]
![image](https://user-images.githubusercontent.com/67182587/101426549-295f5f00-3938-11eb-8e5c-350e5a69a0cc.png)

**Comment by mzhaoshuai** [comment]
![image](https://user-images.githubusercontent.com/22476764/101427020-0f724c00-3939-11eb-9059-70d44be437f4.png)

Just input `0` when you are required to choose the docker image.
